
all:
	@cd client && make all && cd ..
	@cd server && make all && cd ..
	@cd remover && make all && cd ..

clean:
	@cd client && make clean && cd ..
	@cd server && make clean && cd ..
	@cd remover && make clean && cd ..